use_frameworks!

platform :ios, '13.0'

target 'PenguinCore_Example' do
  pod 'PenguinRouting', :path => '../PenguinRouting.podspec'

  target 'PenguinCore_Tests' do
    inherit! :search_paths
    
  end
end
